// Canonical roles as stored in DB (primary_role is a "; "-joined list of these)
export const CANONICAL_ROLES = [
  "Dirección / Realización",
  "Dirección de fotografía / Cámara",
  "Guion",
  "Producción",
  "Montaje / Edición",
  "Sonido",
  "Música / Composición",
  "Arte / Decorados / Vestuario",
  "Efectos visuales / Animación",
  "Distribución / Gestión cultural / Marketing",
  "Docencia / Investigación",
  "Finanzas / Administración",
  "Otros / Multidisciplinar",
] as const;

// Normalized alias tokens (accent-stripped, lowercase) per canonical role
export const ROLE_SYNONYMS: Record<string, string[]> = {
  "Dirección / Realización": [
    "director",
    "directora",
    "directores",
    "directoras",
    "direccion",
    "realizador",
    "realizadora",
    "realizacion",
    "dir",
  ],
  "Dirección de fotografía / Cámara": [
    "dop",
    "dp",
    "fotografia",
    "director de fotografia",
    "directora de fotografia",
    "director foto",
    "directora foto",
    "dirfoto",
    "camara",
    "operador",
    "operadora",
    "operador de camara",
  ],
  "Guion": ["guion", "guionista", "guionistas", "guiones", "escritor", "escritora", "escritura"],
  "Producción": [
    "produccion",
    "productor",
    "productora",
    "productores",
    "productoras",
    "producer",
    "jefe de produccion",
    "jefa de produccion",
  ],
  "Montaje / Edición": [
    "montaje",
    "montador",
    "montadora",
    "edicion",
    "editor",
    "editora",
    "edit",
  ],
  "Sonido": [
    "sonido",
    "sonidista",
    "sonidistas",
    "microfonista",
    "mezclador",
    "mezcladora",
    "tecnico de sonido",
    "tecnica de sonido",
  ],
  "Música / Composición": [
    "musica",
    "composicion",
    "compositor",
    "compositora",
    "bso",
    "banda sonora",
    "musico",
    "musica original",
  ],
  "Arte / Decorados / Vestuario": [
    "arte",
    "decorados",
    "decorador",
    "decoradora",
    "vestuario",
    "figurinista",
    "figurinismo",
    "escenografia",
    "escenografo",
    "escenografa",
    "direccion de arte",
  ],
  "Efectos visuales / Animación": [
    "vfx",
    "efectos visuales",
    "efectos especiales",
    "fx",
    "animacion",
    "animador",
    "animadora",
    "animadores",
    "supervisor vfx",
    "supervisora vfx",
  ],
  "Distribución / Gestión cultural / Marketing": [
    "distribucion",
    "distribuidor",
    "distribuidora",
    "marketing",
    "gestion cultural",
    "comunicacion",
    "prensa",
  ],
  "Docencia / Investigación": [
    "docencia",
    "docente",
    "profesor",
    "profesora",
    "investigacion",
    "investigador",
    "investigadora",
  ],
  "Finanzas / Administración": [
    "finanzas",
    "administracion",
    "administrativo",
    "administrativa",
    "contable",
    "contabilidad",
  ],
  "Otros / Multidisciplinar": ["otros", "multidisciplinar", "multidisciplinario"],
};
