// Synonyms map: PRIMARY_ROLE → normalized alias tokens (accent-stripped, lowercase)
export const ROLE_SYNONYMS: Record<string, string[]> = {
  "Director/a": ["director", "directora", "directores", "directoras", "direccion", "dir"],
  "Director/a de Fotografía": [
    "dop",
    "dp",
    "dirfoto",
    "fotografia",
    "director de fotografia",
    "directora de fotografia",
    "director foto",
    "directora foto",
    "operador de camara",
    "camara",
  ],
  "Guionista": ["guion", "guionista", "guionistas", "guiones", "escritor", "escritora", "escritura"],
  "Productor/a": ["productor", "productora", "productores", "produccion", "producer"],
  "Director/a de Producción": ["director de produccion", "directora de produccion", "jefe de produccion", "jefa de produccion"],
  "Montador/a": ["montaje", "montador", "montadora", "editor", "editora", "edicion"],
  "Sonidista": ["sonido", "sonidista", "sonidistas", "microfonista", "mezclador", "mezcladora"],
  "Compositor/a": ["compositor", "compositora", "musica", "banda sonora", "bso"],
  "Diseñador/a de Producción": ["disenador de produccion", "disenadora de produccion", "diseno de produccion"],
  "Director/a de Arte": ["arte", "director de arte", "directora de arte", "direccion de arte"],
  "Vestuario": ["vestuario", "figurinista", "figurinismo"],
  "Maquillaje / FX": ["maquillaje", "maquillador", "maquilladora", "fx", "efectos especiales", "peluqueria"],
  "Actriz / Actor": ["actor", "actriz", "actores", "actrices", "interprete", "reparto", "casting"],
  "Especialista": ["especialista", "especialistas", "stunt", "stunts", "riesgo"],
  "Colorista": ["colorista", "color", "etalonaje", "etalonador"],
  "Supervisor/a VFX": ["vfx", "supervisor vfx", "supervisora vfx", "efectos visuales", "postproduccion visual"],
  "Animador/a": ["animacion", "animador", "animadora", "animadores"],
  "Fotografía fija": ["fotografia fija", "still", "stills", "fotografo", "fotografa"],
  "Ayudante de dirección": ["ayudante de direccion", "ayudanta de direccion", "ayudante", "1er ayudante", "primer ayudante"],
  "Script": ["script", "continuidad"],
  "Localizaciones": ["localizaciones", "localizador", "localizadora", "scouting"],
  "Otro": [],
};
